package com.xuanxue.ziwei.core

import org.json.JSONArray
import org.json.JSONObject
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Golden-fixture tests: compare the Kotlin port against iztro (TypeScript) expected output.
 * Fixtures generated by iztro scripts/gen-fixtures.ts (MIT).
 */
class FixtureTest {

    private fun starJson(s: ZiweiStars.Star): JSONObject = JSONObject()
        .put("name", s.name)
        .put("type", s.type)
        .put("scope", s.scope)
        .put("brightness", s.brightness)
        .put("mutagen", s.mutagen)

    private fun serialize(a: ZiweiAstro.Astrolabe): JSONObject {
        val palaces = JSONArray()
        for (p in a.palaces) {
            val maj = JSONArray(); p.majorStars.forEach { maj.put(starJson(it)) }
            val min = JSONArray(); p.minorStars.forEach { min.put(starJson(it)) }
            val adj = JSONArray(); p.adjectiveStars.forEach { adj.put(starJson(it)) }
            palaces.put(
                JSONObject()
                    .put("index", p.index)
                    .put("name", p.name)
                    .put("isBodyPalace", p.isBodyPalace)
                    .put("isOriginalPalace", p.isOriginalPalace)
                    .put("heavenlyStem", p.heavenlyStem)
                    .put("earthlyBranch", p.earthlyBranch)
                    .put("majorStars", maj)
                    .put("minorStars", min)
                    .put("adjectiveStars", adj)
                    .put("changsheng12", p.changsheng12)
                    .put("boshi12", p.boshi12)
                    .put("jiangqian12", p.jiangqian12)
                    .put("suiqian12", p.suiqian12)
                    .put("decadal", p.decadal?.let {
                        JSONObject()
                            .put("range", JSONArray().put(it.range[0]).put(it.range[1]))
                            .put("heavenlyStem", it.heavenlyStem)
                            .put("earthlyBranch", it.earthlyBranch)
                    } ?: JSONObject.NULL)
                    .put("ages", JSONArray(p.ages ?: emptyList<Int>())),
            )
        }
        return JSONObject()
            .put("gender", a.gender)
            .put("solarDate", a.solarDate)
            .put("lunarDate", a.lunarDate)
            .put("time", a.time)
            .put("timeRange", a.timeRange)
            .put("earthlyBranchOfSoulPalace", a.earthlyBranchOfSoulPalace)
            .put("earthlyBranchOfBodyPalace", a.earthlyBranchOfBodyPalace)
            .put("soul", a.soul)
            .put("body", a.body)
            .put("fiveElementsClass", a.fiveElementsClass)
            .put("palaces", palaces)
    }

    private fun collectDiffs(expected: JSONObject, actual: JSONObject, path: String, diffs: MutableList<String>) {
        for (key in expected.keys()) {
            val ev = expected.get(key)
            val av = if (actual.has(key)) actual.get(key) else null
            val p = "$path.$key"
            when {
                ev is JSONObject && av is JSONObject -> collectDiffs(ev, av, p, diffs)
                ev is JSONArray && av is JSONArray -> {
                    if (ev.length() != av.length()) {
                        diffs.add("$p: array length ${ev.length()} != ${av.length()}")
                    } else {
                        for (i in 0 until ev.length()) {
                            if (ev.get(i) is JSONObject && av.get(i) is JSONObject) {
                                collectDiffs(ev.getJSONObject(i), av.getJSONObject(i), "$p[$i]", diffs)
                            } else if (ev.get(i) != av.get(i)) {
                                diffs.add("$p[$i]: expected=${ev.get(i)} actual=${av.get(i)}")
                            }
                        }
                    }
                }
                ev == JSONObject.NULL && av == null -> {}
                ev != av -> diffs.add("$p: expected=$ev actual=$av")
            }
        }
    }

    private fun loadFixtures(): List<JSONObject> {
        val text = javaClass.classLoader.getResource("fixtures.jsonl")!!.readText()
        return text.lineSequence().filter { it.isNotBlank() }.map { JSONObject(it) }.toList()
    }

    @Test
    fun `kotlin port matches iztro golden fixtures`() {
        val fixtures = loadFixtures()
        assertTrue(fixtures.isNotEmpty(), "no fixtures loaded")
        var totalDiffs = 0
        for (fx in fixtures) {
            val c = fx.getJSONObject("case")
            val expected = fx.getJSONObject("astrolabe")
            val actual = serialize(
                ZiweiAstro.bySolar(
                    solarDate = c.getString("date"),
                    timeIndex = c.getInt("timeIndex"),
                    gender = c.getString("gender"),
                    fixLeap = c.getBoolean("fixLeap"),
                ),
            )
            val diffs = mutableListOf<String>()
            collectDiffs(expected, actual, fx.getString("id"), diffs)
            if (diffs.isNotEmpty()) {
                totalDiffs += diffs.size
                println("=== ${fx.getString("id")}: ${diffs.size} diffs ===")
                diffs.take(40).forEach { println("  $it") }
            } else {
                println("PASS ${fx.getString("id")}")
            }
        }
        assertEquals(0, totalDiffs, "fixture diffs found (see above)")
    }
}
